version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  assignees:
  - marekdedic
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  assignees:
  - marekdedic
