name: "Collector CI"
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - 'packages/collector/**'
env:
  cache-version: 1

jobs:
  collector-lint:
    name: "Lint collector"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/collector
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Cache NPM dependencies"
        uses: actions/cache@v3
        with:
          path: "~/.npm"
          key: npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('package.json') }}
          restore-keys: |
            npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('package.json') }}
            npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-
            npm-dependencies-${{ runner.os }}-

      - name: "Install NPM dependencies"
        run: |
          npm ci

      - name: "Lint"
        run: |
          npm run lint

  collector-test:
    name: "Test collector"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/collector
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Cache NPM dependencies"
        uses: actions/cache@v3
        with:
          path: "~/.npm"
          key: npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('package.json') }}
          restore-keys: |
            npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('package.json') }}
            npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-
            npm-dependencies-${{ runner.os }}-

      - name: "Install NPM dependencies"
        run: |
          npm ci

      - name: "Run tests"
        run: |
          npm test

      - name: "Upload coverage results"
        uses: codecov/codecov-action@v2.1.0
        with:
          flags: collector
