name: "Config CI"
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - 'config.json'
env:
  cache-version: 1

jobs:
  collect-dry-run:
    uses: skaut/poptavky/.github/workflows/reusable-collect.yml
    secrets:
      PAT: ${{ secrets.PAT_PETA }}
