name: "Run"
on:
  # TODO: Add schedule
  workflow_dispatch:
env:
  cache-version: 1

jobs:
  build:
    name: "Collect"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2.3.4

      - name: "Cache NPM dependencies"
        uses: actions/cache@v2.1.6
        with:
          path: "~/.npm"
          key: npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('package.json') }}
          restore-keys: |
            npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('package.json') }}
            npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-
            npm-dependencies-${{ runner.os }}-

      - name: "Install NPM dependencies"
        run: |
          npm ci --no-dev

      - name: "Collect"
        run: |
          npm run collect
        env:
          PAT: ${{ secrets.PAT_MAREKDEDIC }}

      #- name: "Show results"
        #run: |
          #cat collected.json
